name: Setup

inputs:
  python-version:
    required: false
    default: '3.9'
  numpy-version:
    required: false
    default: '1.25.1'
  SimpleITK-version:
    required: false
    default: '2.2.0'
  full_install:
    required: false
    default: true

runs:
  using: composite


  steps:
    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@v4.3.0
      with:
        python-version: ${{ inputs.python-version }}
        check-latest: true
        cache: pip
        cache-dependency-path: |
          pyproject.toml


    - name: Install Numpy
      if: ${{ inputs.numpy-version != 'nightly' }}
      run: |
        pip install --no-index numpy==${{ numpy-version }}
      shell: bash

    - name: Install SimpleITK
      if: ${{ inputs.numpy-version != 'nightly' }}
      run: |
        pip install --no-index numpy==${{ SimpleITK-version }}
      shell: bash
