# Strip the 'v' from the version tag
{% if GIT_DESCRIBE_TAG is defined %}
{%   set version = GIT_DESCRIBE_TAG[1:] %}
{% else %}
{%   set version = "0.0.0" %}
{% endif %}


package:
  name: medipt
#  version: {{ environ["PACKAGE_VERSION"] }}
  version: {{ version  }}

source:
    path: ..

build:
    number: 0
    string: py{{ environ.get('PYTHON_VERSION').replace('.', '') }}
    noarch: python
#    script: python -m pip install --no-deps --ignore-installed .
#    script: {{ PYTHON }} -m pip install .
#    script: {{ PYTHON }} -m pip install -vv --no-deps --ignore-installed -e .
    script: {{ PYTHON }} -m pip install -vv --no-deps --ignore-installed .
#    script: {{ PYTHON }} -m pip install -vv .
#    script: pip install .

    run_exports:
      - libgcc
      - libgcc-ng




requirements:
#  build:
#    - SimpleITK
#    - python

  host:
    - python {{ environ.get('PYTHON_VERSION') }}
    - setuptools
    - pip
    - SimpleITK >=2.2.0
    - numpy >=1.20.0
    - scipy >=1.6.0

  run:
    - python {{ environ.get('PYTHON_VERSION') }}
    - numpy >=1.20.0
    - SimpleITK >=2.2.0
    - scipy >=1.6.0


test:
  imports:
    - medipt
    - medipt.transforms
    - medipt.transforms.spatial
    - SimpleITK



about:
  home: https://github.com/kleingeo/ImageProcessingTools
  license: BSD 3-Clause
  license_file: LICENSE
  summary: Medical Imaging Processing Tools