name: Publish to PyPI

on:
  push:
  workflow_dispatch:
  
jobs:
    
  build:
    runs-on: ubuntu-latest

    continue-on-error: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
            fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: python3 -m pip install --user --upgrade pip build twine setuptools
        shell: bash

      - name: Build wheel
        run: python -m build --sdist --wheel --outdir dist/ .
        shell: bash

      - name: Publish to Test PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository-url: https://test.pypi.org/legacy/


      - name: GitHub tag name example
        run: |
          echo "Tag name from github.ref_name: ${{  github.ref_name }}"
          
      

      - name: Publish to PyPI
        if: startsWith(github.ref, 'refs/tags/v') || contains(github.ref, 'refs/tags/v*')
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
