name: Build and Publish (Depreciated)

on:
#  push:
#    branches:
#      - main
#      - develop
  workflow_dispatch:



jobs:
  build_wheels:
    name: Build wheel for ${{ matrix.python }}
    runs-on: ubuntu-latest
    env:
      IS_PUSH: ${{ github.event_name == 'push' || startsWith(github.ref, 'refs/tags/v') }}
      IS_WORKFLOW_DISPATCH: ${{ github.event_name == 'workflow_dispatch' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0


      - name: Set Python Version
        run: echo "PYTHON_VERSION=${{ matrix.python }}" >> $GITHUB_ENV
        shell: bash -el {0}

#      - name: Set up Python
#        uses: conda-incubator/setup-miniconda@v2
#        with:
#          auto-update-conda: true
#          miniconda-version: "latest"
#          python-version: "3.9"
#          activate-environment: wheel-env
#          environment-file: ./.github/etc/miniconda-environment.yml


      - name: Setup python
        uses: actions/setup-python@v3


      - name: Build sdist
        run: |
          python -m build --sdist --wheel --outdir ./dist/py-3.9
        shell: bash -el {0}


      - name: Test build
        run:
          python -m pip install dist/py-3.9/*.whl
          python -c "import medipt"
          python -c "import SimpleITK"
        shell: bash -el {0}



#      - name: Publish to PyPI
#        if: startsWith(github.ref, 'refs/tags/v') || contains(github.ref, 'refs/tags/v*')
#        uses: pypa/gh-action-pypi-publish@release/v1
#        with:
#          password: ${{ secrets.PYPI_API_TOKEN }}
#          packages-dir: ./dist/py-${{ matrix.python }}